config/routes.rb
DroidSpy::Application.routes.draw do

  resources :photos

  resources :articles do
    resources :comments

  end
  
  get "welcome/index"

   root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
has_many :comments, dependent: :destroy
validates :title, presence: true,
                    length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
 


def new
	@article = Article.new
end

def show
  @article = Article.find(params[:id])
end





def create
  @article = Article.new(article_params)
 
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end


def index
  @articles = Article.all
end


 
def edit
  @article = Article.find(params[:id])
end



def update
  @article = Article.find(params[:id])
 
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end




def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end



private
  def article_params
    params.require(:article).permit(:title, :text)
  end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
 

def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end



  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:photo_admin)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photo_admin_helper.rb
module PhotoAdminHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/_header.html.erb
<h1>DroidSpy</h1>
<p> A Platform to Share Information and Watch the Skies for Asteroids.</p>




<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7TcpaYv9ElajJ81kHLWnWl7l2VyMcGnPN17E1u2iCCT4PeZgJyg">


<img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSExnfY6aqULMXBzyEaXE2b9W2HlfVpQanucSa_nFv4ID0950DmMQ">

app/views/articles/edit.html.erb
<%=  render 'header' %>

<h1>Edit Asteroid</h1>
<%= render 'form' %>


 
<%= link_to 'Back', articles_path %>




 

app/views/articles/index.html.erb


<h1>DroidSpy</h1>
<p> A Platform to Share Information and Watch the Skies for Asteroids. Have fun While searching the Heavens!!!</p>




<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7TcpaYv9ElajJ81kHLWnWl7l2VyMcGnPN17E1u2iCCT4PeZgJyg">


<img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSExnfY6aqULMXBzyEaXE2b9W2HlfVpQanucSa_nFv4ID0950DmMQ">

<h1>Listing Asteroids</h1>

<%= link_to 'New article', new_article_path %>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%=  render 'header' %>


<h1>New Asteroid</h1>
 
<%= render 'form' %>
 


<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>DroidSpy</h1>
<p> A Platform to Share Information and Watch the Skies for Asteroids.</p>




<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7TcpaYv9ElajJ81kHLWnWl7l2VyMcGnPN17E1u2iCCT4PeZgJyg">


<img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSExnfY6aqULMXBzyEaXE2b9W2HlfVpQanucSa_nFv4ID0950DmMQ">

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>
 

<h2>Add a comment:</h2>
<%= render "comments/form" %>
  
 
<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DroidSpy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo_admin %><br>
    <%= f.text_field :photo_admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>Photo admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.photo_admin %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo admin:</strong>
  <%= @photo.photo_admin %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/welcome/index.html.erb
<h1>DroidSpy</h1>
<p> A Platform to Share Information and Watch the Skies for Asteroids.</p>




<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7TcpaYv9ElajJ81kHLWnWl7l2VyMcGnPN17E1u2iCCT4PeZgJyg">


<img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSExnfY6aqULMXBzyEaXE2b9W2HlfVpQanucSa_nFv4ID0950DmMQ">


<%= link_to 'My Blog', controller: 'articles' %>